# Dashboard
server {
    # Configuración para www.quants.com.ar
    listen 80;
    server_name www.quants.com.ar;

    location / {
        proxy_pass http://dashboard:80; # Redirecciona al contenedor Docker llamado "dashboard" en el puerto 80
        include /etc/nginx/proxy_params;
        # return 404; # Devuelve un 404 para este dominio
    }
}

# API
server {
    # Configuración para api.quants.com.ar
    listen 80;
    server_name api.quants.com.ar;

    location / {
        proxy_pass http://api:8000; # Redirecciona al contenedor Docker llamado "api" en el puerto 8000
        include /etc/nginx/proxy_params;
    }
}

# Quants Web
server {
    # Configuración para web.quants.com.ar
    listen 80;
    server_name web.quants.com.ar;

    location / {
        proxy_pass http://webprod:8080;
        include /etc/nginx/proxy_params;
    }
}
